economist_task:
  description: >
    You are an extremely experienced economist with expertise in analyzing the impact of government policies on
    the economy. Using your knowledge and the tools available to you, provide a comprehensive analysis
    of the current economic implications of {policy_topic1}, considering variables like {economic_variable1}
    and {economic_variable2}. Focus on key macroeconomic variables and indicators, and draw insights that
    would be valuable for policymakers and the public.
  expected_output: >
    As an extremely experienced economist, I have conducted a thorough analysis of the current economic implications
    of the {policy_topic1}, considering variables like {economic_variable1} and {economic_variable2} and using
    the latest available data and information.
    Do not mention which Task you are completing in your response.
    Only provide the output of the task. Do not ask for clarification. Do not
    include comments or reflective statements on your analysis, any of your answers or your report. For example, do not use language like:
    "Overall, this is a well-structured and comprehensive final answer that effectively addresses the task at hand." or
    "I hope this response meets your expectations." or "Overall, the analysis provides a comprehensive understanding" or 
    "The final report presents the analysis in a clear format, organizing information"
    Do not provide a summary of the report or analysis or any other comments after the conclusion of your analysis.
  agent: economist

financial_analyst_task:
  description: >
    As a leading financial analyst, you are tasked with evaluating the market and economic effects of recent {policy_topic2}
    decisions in response to the {policy_topic1} policy. Utilize your expertise and the available tools to offer a detailed
    assessment, considering variables like {economic_variable1} and {economic_variable2}, and highlighting areas where you
    agree or disagree with the economist's analysis.
  expected_output: >
    As a financial analyst specializing in the evaluation of monetary policy and its impact on financial markets, I have
    carefully reviewed the economist's analysis of the {policy_topic1}, and its economic implications, considering variables
    like {economic_variable1} and {economic_variable2}. Based on my expertise and experience, I have identified key areas of
    agreement and disagreement with the economist's analysis.
    Do not mention which Task you are completing in your response.
    Only provide the output of the task. Do not ask for clarification. Do not
    include comments or reflective statements on your analysis, any of your answers or your report. For example, do not use language like:
    "Overall, this is a well-structured and comprehensive final answer that effectively addresses the task at hand." or
    "I hope this response meets your expectations." or "Overall, the analysis provides a comprehensive understanding" or 
    "The final report presents the analysis in a clear format, organizing information"
    Do not provide a summary of the report or analysis or any other comments after the conclusion of your analysis.
  agent: financial_analyst

